Kamikaze94/WolfHUD

lua/PrePlanManager.lua
Issue: It would not load the final item in the json file.
=> Fixed Preplanning Manager

loc/russian.json
=> New version

loc/russian.json
=> New update russian

loc/russian.json
=> New Kazo russian loc

loc/RealWeaponNames.json, loc/dutch.json, loc/english.json, loc/french.json, loc/german.json, loc/italian.json, loc/korean.json, loc/russian.json, loc/spanish.json, mod.txt
=> Fix invalid JSON

lua/EquipmentTweaks.lua
=> fix shaped charge suppression in stealth

README.md
* Added updated images
* Fixed Markdown problems
* Certain texts ordinated
=> Tweaks into the Readme

loc/english.json
Happens in the beginning of Watchdogs Day 2. Other languages will need this too.
=> Added english string for Anticipate Assault State

lua/EnhancedObjective.lua
Small change to make this work without crashing https://modworkshop.net/mydownloads.php?action=view_down&did=20849#cid57498
but in anyway should be changed because it's incorrect.
=> Fix for recreating objectives hud

loc/russian.json
new upd rus
[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.]
Fixes # [issue]
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> new upd rus

loc/spanish.json
I've updated the spanish translation with the most recent addition
PS: can you credit me for the spanish translation?
=> Updated Spanish.json

lua/CustomWaypoints.lua
Added Hila and Ethan to Custom Waypoints
Fixes # [issue]
Please delete options that are not relevant.
Verifying in game the correction
=> Added Hila and Ethan to Custom Waypoints

lua/EnemyHealthbar.lua
Added Hila and Ethan to EnemyHealthbar
Checked in game the corrections
=> Added Hila and Ethan to EnemyHealthbar

loc/portuguese.json
Some fixes to adapt weird expressions
=> Portuguese loc fixes

Core.lua
While reading the code, i stumbled upon this line.
It just didnt seem right to me, so i changed it to what seems logical to me. Please validate.
Bug fix
It did not.
=> Gadgets: Fix laser menu callback null checks?

lua/RichPresence.lua
fixes old crash bug with rich presence
Fixes #777 #753
i dont have installed game so i ask to test in #777
=> check what lobby_handler is not nil

OptionMenus.lua, lua/VanillaHUD.lua
Allows the ping display option to function with the vanilla hud
ref: https://github.com/Kamikaze94/WolfHUD/issues/129
=> Ping display for Vanilla HUD

lua/PrePlanManager.lua, mod.txt
When you use a controller and click delete plan when there is only one item saved it crashes
Fixes issues #746
Please delete options that are not relevant.
Tested with the latest commit
=> Fixed preplanning controller crash

loc/spanish.json
Updated spanish with the recent changes.
=> Updated Spanish

lua/RichPresence.lua
=> typo MAYHAM -> MAYHEM
